### ISSUE TITLE
Could not locate the bindings file

### ISSUE THREAD

**Issue by parichit13** [stevetarver/excel-as-json#10]
I have been trying to parse a simple excel file with just dummy data and 2 fields as:

firstName     lastName
John             Doe

but the result was coming as empty array: `[]`. So I tried to check out the library files and found that at excel library there was an parseError which was not being logged. It is as follows:

`{ [Error: Could not locate the bindings file. Tried:
 → /mnt/c/Users/gamepr0/Mirrors/excel-to-json/node_modules/libxmljs/build/xmljs.node
 → /mnt/c/Users/gamepr0/Mirrors/excel-to-json/node_modules/libxmljs/build/Debug/xmljs.node
 → /mnt/c/Users/gamepr0/Mirrors/excel-to-json/node_modules/libxmljs/build/Release/xmljs.node
 → /mnt/c/Users/gamepr0/Mirrors/excel-to-json/node_modules/libxmljs/out/Debug/xmljs.node
 → /mnt/c/Users/gamepr0/Mirrors/excel-to-json/node_modules/libxmljs/Debug/xmljs.node
 → /mnt/c/Users/gamepr0/Mirrors/excel-to-json/node_modules/libxmljs/out/Release/xmljs.node
 → /mnt/c/Users/gamepr0/Mirrors/excel-to-json/node_modules/libxmljs/Release/xmljs.node
 → /mnt/c/Users/gamepr0/Mirrors/excel-to-json/node_modules/libxmljs/build/default/xmljs.node
 → /mnt/c/Users/gamepr0/Mirrors/excel-to-json/node_modules/libxmljs/compiled/4.5.0/linux/x64/xmljs.node]
  tries:
   [ '/mnt/c/Users/gamepr0/Mirrors/excel-to-json/node_modules/libxmljs/build/xmljs.node',
     '/mnt/c/Users/gamepr0/Mirrors/excel-to-json/node_modules/libxmljs/build/Debug/xmljs.node',
     '/mnt/c/Users/gamepr0/Mirrors/excel-to-json/node_modules/libxmljs/build/Release/xmljs.node',
     '/mnt/c/Users/gamepr0/Mirrors/excel-to-json/node_modules/libxmljs/out/Debug/xmljs.node',
     '/mnt/c/Users/gamepr0/Mirrors/excel-to-json/node_modules/libxmljs/Debug/xmljs.node',
     '/mnt/c/Users/gamepr0/Mirrors/excel-to-json/node_modules/libxmljs/out/Release/xmljs.node',
     '/mnt/c/Users/gamepr0/Mirrors/excel-to-json/node_modules/libxmljs/Release/xmljs.node',
     '/mnt/c/Users/gamepr0/Mirrors/excel-to-json/node_modules/libxmljs/build/default/xmljs.node',
     '/mnt/c/Users/gamepr0/Mirrors/excel-to-json/node_modules/libxmljs/compiled/4.5.0/linux/x64/xmljs.node' ] }`

I request you please fix this problem ASAP as my project is stuck due to this error

**Comment by stevetarver** [comment]
First: this is open source - feel free to submit a pull request that fixes the problem.
If you can't figure it out, please submit a project that reproduces this error and I will try to look at it tonight.

**Comment by stevetarver** [comment]
Parichit, on re-reading your description, I see that your problem is an `excel` package problem. I did not write this package and cannot fix it directly.
