### ISSUE TITLE
on nodejs version 7.5.0 ,can't read excel

### ISSUE THREAD

**Issue by woshizilong** [stevetarver/excel-as-json#14]
it can't read excel on nodejs 7.5.0

**Comment by stevetarver** [comment]
woshizilong, sorry I took so long to respond.

I updated to node 7.9.0 and many tests failed - the excel package was returning an empty array.

I deleted `node_modules/`, then `npm install` and all tests passed.

Is this the same problem you are having?

**Comment by stevetarver** [comment]
I noticed that during the npm install, the latest libxmljs was pulled down, 0.18.4 <- this might be the source of the fix.

**Comment by woshizilong** [comment]
Thank you for the answer, I also empty the node_modules. Now is OK.
