### ISSUE TITLE
Is there an easy way to add a root node to the json file?

### ISSUE THREAD

**Issue by anuragongit** [stevetarver/excel-as-json#15]
Hi,

Currently, the converter is outputting json as:

```
[
  {
    "name": "John Doe",
    "age": "30"
  },
  {
   "name": "Alex Len",
    "age": "27"
  },
  {
   "name": "Debbie John",
    "age": "36"
  }

]
```

But, is there a way to add a root node through configuration variables, so that the json looks like this:

```
[
  {
    "user": [
      {
        "name": "John Doe",
        "age": "30"
      },
      {
        "name": "Alex Len",
        "age": "27"
      },
      {
        "name": "Debbie John",
        "age": "36"
      }
    ]
  }
]
```

**Comment by duduzeta** [comment]
I would love to be able to do that too.

**Comment by binarymax** [comment]
Isn't this easy with a post-processing step?  Seems better to leave it up to the client rather than try to solve it with configuration.

**Comment by anuragongit** [comment]
Yeah it can be a post-proccessing step. That's what I did when I wanted it this way. But having it is an option in the config would have saved all that PP. Not a deal breaker but I was curious if there was something that I was missing.

**Comment by stevetarver** [comment]
There is always a tension between simplicity and feature count.

I prefer small, simple packages that you chain together as opposed to each
package being able to execute each feature requested. Small and simple
usually means stable, solid, easy to fix. Feature rich packages are always
more buggy, difficult to fix, extend, etc. For each feature added, there is
a non-linear number of test cases added.

 IOW: I completely agree with Max's response.
