### ISSUE TITLE
Can we export each rows to a separate JSON file?

### ISSUE THREAD

**Issue by ishanshams** [stevetarver/excel-as-json#16]
Hello, I have an excel sheet that is row oriented. I am trying to export each rows into it's own separate JSON file.

Any suggestions or help would be highly appreciated.

**Comment by stevetarver** [comment]
Two approaches: 

* Convert your spreadsheet, capture the parsed output, iterate over the list and save each row to a separate file.
* Put each row on a separate sheet, call once for each sheet and provide a unique file name for each call

Hope that helps
