### ISSUE TITLE
number array with empty values

### ISSUE THREAD

**Issue by screenworker** [stevetarver/excel-as-json#17]
| numbers[] |
|-----------|
| 1;2| 
| |
| 3;5     | 

Shold be:

```
[{
  "numbers": [
    1,
    2
  ]
},
{
  "numbers": []
},
{
  "numbers": [
  3,
  5
  ]
}]
```
and not:

```
[{
  "numbers": [
    1,
    2
  ]
},
{
  "numbers": [
  ""
  ]
},
{
  "numbers": [
  3,
  5
  ]
}]
```

**Comment by stevetarver** [comment]
screenworker: There is an option in the current version to `omitEmptyFields`; omit empty values and name-value pairs where the value is empty.
 
The data in this test is what would be returned in your example - the excel package I use returns '' for empty cells. Note the use of default options
```coffeescript
  it 'should omit empty values when directed', ->
    data = [[ 'numbers[]' ],
            [ '1;2'],
            [ ''   ],
            [ '3;5']]
    result = convert data, DEFAULT_OPTIONS
    console.dir result
```
produces
```json
[ { numbers: [ 1, 2 ] },
  { numbers: [ '' ] },
  { numbers: [ 3, 5 ] } ]
```
setting omitEmptyFields = true has this effect 
```coffeescript
  it 'should omit empty values when directed', ->
    o =
      omitEmptyFields: true
    data = [[  'numbers[]' ],
            [ '1;2'],
            [ ''   ],
            [ '3;5']]
    result = convert data, o
    console.dir result
```
produces
```json
[ { numbers: [ 1, 2 ] }, 
  {}, 
  { numbers: [ 3, 5 ] } ]
```

Does this help?

**Comment by screenworker** [comment]
Hey Stevetarver,

i also tried with and without "omitEmptyFields" option in version 2.0.0 and 2.0.1 but always the same result. Maybe my option combination ignores that option feature:

```
var src = 'test.xlsx';
var destDir = './output';
var options =  {
            sheet: 1,
            isColOriented: false,
            omitEmtpyFields: true
        };

        var destPath = destDir + '/' + sheet + '.json';
        convert(src, destPath, options, function( err ) {
            if (err) {
                console.log(err);
            }
        });
```

**Comment by stevetarver** [comment]
Your code looks right to me; a project would simplify debugging. Attached is a project that shows the code is working as expected - what is shown above. `npm install` it, then `coffee issue17.coffee` to produce the above output.

[excel-as-json.17.zip](https://github.com/stevetarver/excel-as-json/files/998977/excel-as-json.17.zip)

**Comment by screenworker** [comment]
Thank you for your example project :)

You are right with coffee!
But have you ever tried it with node? 
Please try it with my example below (`npm install` and `node issue17.js`) and you will be able to see the same result as in my first post.

[excel-as-json_node.17.zip](https://github.com/stevetarver/excel-as-json/files/998985/excel-as-json_node.17.zip)

**Comment by screenworker** [comment]
It´s an spelling issue of the option parameter :(
`omitEmtpyFields: true` has to be `omitEmptyFields: false`
My mistake. I am sorry.
