### ISSUE TITLE
fs.existsSync is not a function

### ISSUE THREAD

**Issue by Shobhit98** [stevetarver/excel-as-json#18]
![untitled](https://user-images.githubusercontent.com/16690189/27085248-5eb6e0f0-506c-11e7-92a0-95fd56b17b7b.jpg)

**Comment by stevetarver** [comment]
Apologies for the horrendously long hiatus. 
If you google the error, you will see lots of suggestions on where to start. I would need a project with sample data to do anything with this report. I'm sure you are long past this issue and thus closing it.
