### ISSUE TITLE
npm install excel-as-json failed

### ISSUE THREAD

**Issue by dadclass** [stevetarver/excel-as-json#2]
Hi,

I am unable to install and excerpt of the error below.  I have also attached the npm-debug.log, would you help please?
[npm-debug.log.txt](https://github.com/stevetarver/excel-as-json/files/264653/npm-debug.log.txt)

Thanks

H:\node\testlab\excelJson>npm install excel-as-json --save-dev
npm WARN package.json excel_json@1.0.0 No repository field.
npm WARN package.json excel_json@1.0.0 No README data
npm WARN deprecated graceful-fs@3.0.8: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
-
> libxmljs@0.14.3 install H:\node\testlab\excelJson\node_modules\excel-as-json\node_modules\excel\node_modules\libxmljs
> node-gyp rebuild

H:\node\testlab\excelJson\node_modules\excel-as-json\node_modules\excel\node_modules\libxmljs>if not defined npm_config_node_gyp (node "I:\nodejs-0.10.24\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (rebuild)
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
...

**Comment by stevetarver** [comment]
This is a problem building one of my dependencies, dependecies: the `excel` package uses `libxmljs` at v 0.14.0 (resolved to 0.14.3 in your build, current version 0.18.0). 

From your npm-debug.log.txt

> 3212 error Failed at the libxmljs@0.14.3 install script 'node-gyp rebuild'.
> 3212 error This is most likely a problem with the libxmljs package,

If you search through that log for libxmljs, you don't find much more info than this. On my mac, node-gyp writes errors to stdout, so you could retry and look for those node-gyp errors for more details.

It may be a node-gyp dependency problem - you should verify that all required dependencies are installed. Details are [here](https://github.com/nodejs/node-gyp#installation).

libxmljs has had issues building on windows. [This open issue](https://github.com/libxmljs/libxmljs/issues/392) looks similar to your problem, was opened in v 0.17.0, so getting the `excel.js` author to update his version of libxmljs won't help.

If you continue to want to use this package, see an update that fixes your problem and the [excel.js] (https://github.com/trevordixon/excel.js) project updates its dependency, create a new issue and I will update as well.

Closing this issue; nothing for me to do.

**Comment by dadclass** [comment]
Hi Steve,

Thanks for your reply and explanation.

Sam
