### ISSUE TITLE
Return empty array

### ISSUE THREAD

**Issue by choipd** [stevetarver/excel-as-json#22]
Thank you for your great work. This library saved my time! Then I've got a problem from today.
My issue is that convertExcel() function callback returns empty array with no error.  It could be a similar issue #7.  Can I have any workaround?

Test environment
* node: v8.1.2
* excel-as-json: 2.0.1
* excel: 0.1.7

**Comment by choipd** [comment]
Never mind, it's ok now. I am not sure what's the problem.

**Comment by steventarver** [comment]
@choipd I have seen this happen when upgrading one component (node, excel-as-json, dependencies). Deleting node_imports and then doing a fresh npm install for your project has fixed this for myself and others.

Glad you found the package useful.
