### ISSUE TITLE
Question: Passing an Object instead of src

### ISSUE THREAD

**Issue by olivlaytchev** [stevetarver/excel-as-json#26]
I have been trying to figure out a way to pass in my .xlsx file as an Object - as it is uploaded by the client (after which it will be converted). I haven't been able to get very far, are there any suggestions on how I could tackle this?

What if I were to store the .xlsx file in Mongo (although I am not entirely sure how it will be saved in there)?

**Comment by steventarver** [comment]
These functions are pretty tightly coupled to the [excel](https://www.npmjs.com/package/excel) package. You could write your uploaded xlsx doc to file and then load it, or you could convert the functions in this package to work on your xlsx object, etc...
