### ISSUE TITLE
Date is converted to some unknown number

### ISSUE THREAD

**Issue by uditkumawat** [stevetarver/excel-as-json#27]
This is the first time I am using this module.I am having a excel file which contains date format column as this (DD/MM/YYYY) but after conversion to json,this date changed to some number - 42912.

26/6/2017   changed to 42912.

What could be the issue ?

**Comment by stevetarver** [comment]
This is excel's internal storage format for dates. From cpearson:

> Excel stores dates and times as a number representing the number of days since 1900-Jan-0, plus a fractional portion of a 24 hour day: ddddd.tttttt . This is called a serial date, or serial date-time. The integer portion of the number, ddddd, represents the number of days since 1900-Jan-0.

http://www.cpearson.com/excel/datetime.htm

**Comment by thearabbit** [comment]
Excuse me, how to solve this?
