### ISSUE TITLE
not able to force numbers as strings

### ISSUE THREAD

**Issue by mcafeerun** [stevetarver/excel-as-json#30]
Hi,

This is very cool utility! thanks much for offering this!!

In excel, i have all cells formatted as string (to avoid auto formatting of numbers/date). While converting this excel to json, the string column is auto recognized as numeric column (based on cell value) and the converter is stripping off leading zeros (which is obvious for a numeric json node value).

Is there a way i can force converter to treat the number as string and retain those leading zeros.

Note: I'm using Excel workbook *.xlsx

Thanks!

**Comment by art12354** [comment]
I am having the same issue.

I have a bunch of product ID's that may or may not contain just numbers or a combination of letters and numbers. After the conversion they are all different variable types.

**Comment by mnatesh** [comment]
I am having the same issue.  all the leading zeros have been truncated and automatically converted as numbers,  

@mcafeerun :  Did you find any solution/workaround for this issue.   Appreciate your help !

**Comment by stevetarver** [comment]
Fixed in v2.0.2. I have added a `convertTextToNumber` option. When set to false, things that are text in the excel spreadsheet will not be converted to a numeric type.

Thanks for your bug reports.

**Comment by mnatesh** [comment]
Thank you so much,  it worked. !
