### ISSUE TITLE
TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by boulepick** [stevetarver/excel-as-json#33]
Good day,

i believe there is a bug in the convert function:
node: 8.11.2
excel: 0.1.7
excel-as-json: 2.0.2

```
  convert = function(data, options) {
    // console.log(data);
    var index, item, j, k, keys, len, len1, result, row, rows, value;
    if (options.isColOriented) {
      data = transpose(data);
    }
    keys = data[0];
    rows = data.slice(1);
    result = [];
    for (j = 0, len = rows.length; j < len; j++) {
      row = rows[j];
      item = {};
      for (index = k = 0, len1 = row.length; k < len1; index = ++k) {
        console.log(value); // undefined
        assign(item, keys[index], value, options);
      }
      result.push(item);
    }
    return result;
  };
```

so when it goes to the assign function i get the error:

...\node_modules\node-promise\promise.js:204
          throw error;
          ^

TypeError: Cannot read property 'length' of undefined
    at convertValue (...\node_modules\excel-as-json\lib\excel-as-json.js:49:15)
    at assign (...\node_modules\excel-as-json\lib\excel-as-json.js:106:33)
    at convert (...\node_modules\excel-as-json\lib\excel-as-json.js:143:9)
    at ...\node_modules\excel-as-json\lib\excel-as-json.js:218:20
    at ...\node_modules\excel\excelParser.js:163:3
    at Immediate._onImmediate (...\node_modules\node-promise\promise.js:164:27)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)

**Comment by boulepick** [comment]
updated everything
excel and excel-as-json.
now everything seems to work

**Comment by stevetarver** [comment]
This is probably the best bug report I have received (only missing the source excel file) - really appreciate that.

It is curious to me how many of these issues are solved by "turning it off and turning it back on again". Glad you were able to solve your problem.

**Comment by boulepick** [comment]
[testfile.xlsx](https://github.com/stevetarver/excel-as-json/files/2065250/testfile.xlsx)

attached the file if you still want to debug.

Thanks for the great work
