### ISSUE TITLE
Uncaught ReferenceError: require is not defined

### ISSUE THREAD

**Issue by drexel75** [stevetarver/excel-as-json#35]
Hi,
I am getting this error when trying to convert an Excel file.
I am certainly missing something and I am quite unexperienced on the matter.
Could you please help ?
Thank you !

**Comment by stevetarver** [comment]
@drexel75, 

The good news is that this is not an 'excel-as-json' problem - you don't have to wait for me to fix something.

The bad news is that you are going to have to learn a little and rethink your strategy. Your fastest solution is to google the error phrase you used as an issue title, see stackoverflow, etc. E.g. https://stackoverflow.com/questions/19059580/client-on-node-uncaught-referenceerror-require-is-not-defined
